name: flutter_init
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  lottie: ^2.3.1
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  pin_code_fields: ^7.4.0
  fluttertoast: ^8.2.1

  # dependency injection
  get_it: ^7.2.0

  # local storage
  sqflite: ^2.2.6
  shared_preferences: ^2.1.0

  # state manager
  flutter_riverpod: ^2.3.2

  # navigation
  go_router: ^6.5.2

  # networks
  dio: ^5.1.1
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.3

  # firebase config
#  firebase_core: ^2.7.0
#  firebase_messaging: ^14.2.5
#  firebase_crashlytics: ^3.0.17
  flutter_local_notifications: ^13.0.0

  # maps
  google_maps_flutter: ^2.2.4
  geocoding: ^2.0.5
  geolocator: ^9.0.2

  # functional
  fpdart: ^0.5.0
  intl: ^0.18.0
  equatable: ^2.0.5
  collection: ^1.17.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  rename: ^2.1.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
